/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "aadfpwukoffzulsicebs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZGZwd3Vrb2ZmenVsc2ljZWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0Nzg3NzIsImV4cCI6MjA3OTA1NDc3Mn0.NT_QxpNpXbxgAryBaQtVok_COqi9tmCjCg-4nnD-jPE"